project_id = "ewoogkppvrvdrjetepkb"

[functions.get-maps-key]
verify_jwt = false

[functions.analyze-symptoms]
verify_jwt = false

[functions.hospital-analytics]
verify_jwt = false

[functions.predict-wait-times]
verify_jwt = false

[functions.send-external-notification]
verify_jwt = true